# frozen_string_literal: true
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

puppetversion = ENV['PUPPET_GEM_VERSION'] || '>= 7.24'
gem 'puppet', puppetversion, require: false, groups: [:test]

gem 'facterdb',           '>= 3.1', '< 5.0'
gem 'metadata-json-lint', '>= 4.0', '< 6'
gem 'puppet-strings',     '>= 5.0', '< 7'
gem 'parallel_tests',     '>= 4.2', '< 6'
gem 'puppet_fixtures',    '>= 0.1', '< 3'
gem 'puppet-syntax',      '>= 6.0', '< 8'
gem 'rake',               '~> 13.0', '>= 13.0.6'
gem 'rspec-github',       '>= 2.0', '< 4'
gem 'rspec-puppet',       '~> 5.0'
gem 'rspec-puppet-facts', '>= 5.4', '< 7'
gem 'rubocop',            '~> 1.50.0'
gem 'rubocop-rake',       '~> 0.6.0'
gem 'rubocop-rspec',      '~> 2.20.0'
gem 'syslog',             '~> 0.3.0'
gem 'puppet_metadata',    '~> 5.3', require: false
gem 'voxpupuli-puppet-lint-plugins', '>= 6.0', '< 8'
gem 'metadata_json_deps', require: false
# vim: syntax=ruby
