---
name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: ./site/profiles

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup_matrix:
    defaults:
      run:
        working-directory: './site/profiles'
    name: 'Setup Test Matrix'
    runs-on: ubuntu-latest
    timeout-minutes: 40
    outputs:
      puppet_unit_test_matrix: ${{ steps.get-outputs.outputs.puppet_unit_test_matrix }}
      github_action_test_matrix: ${{ steps.get-outputs.outputs.github_action_test_matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
          working-directory: ./site/profiles
      - name: Display Ruby environment
        run: bundle env
      - name: Run static validations
        run: bundle exec rake validate lint check
      - name: Run rake rubocop
        run: bundle exec rake rubocop
      - name: Setup Test Matrix
        id: get-outputs
        run: bundle exec metadata2gha --pidfile-workaround false

  unit_openvox:
    needs: setup_matrix
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.puppet_unit_test_matrix)}}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
      PUPPET_VERSION: "~> ${{ matrix.puppet }}.0"
    name: OpenVox ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v6
      - name: Setup ruby
        uses: overlookinfra/setup-ruby@main
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
          bundler-cache: true
          working-directory: ./site/profiles
          setup-script: |
            git clone --depth 1 -b bundler-plugin-eval-hooks https://github.com/ccutrer/rubygems.git /tmp/rubygems
            gem -C /tmp/rubygems/bundler build bundler.gemspec 
            gem install /tmp/rubygems/bundler/bundler-2.6.0.dev.gem
            bundle plugin install bundler-alias
            bundle config set aliases 'puppet:openvox'
      - name: Run tests
        run: bundle exec rake parallel_spec

  unit_puppet:
        needs: setup_matrix
        runs-on: ubuntu-latest
        timeout-minutes: 40
        strategy:
          fail-fast: false
          matrix:
            include: ${{fromJson(needs.setup_matrix.outputs.puppet_unit_test_matrix)}}
        env:
          BUNDLE_WITHOUT: development:system_tests:release
          PUPPET_VERSION: "~> ${{ matrix.puppet }}.0"
        name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
        steps:
          - uses: actions/checkout@v6
          - name: Setup ruby
            uses: overlookinfra/setup-ruby@main
            with:
              ruby-version: ${{ matrix.ruby }}
              bundler: none
              bundler-cache: true
              working-directory: ./site/profiles
              setup-script: |
                git clone --depth 1 -b bundler-plugin-eval-hooks https://github.com/ccutrer/rubygems.git /tmp/rubygems
                gem -C /tmp/rubygems/bundler build bundler.gemspec 
                gem install /tmp/rubygems/bundler/bundler-2.6.0.dev.gem
                bundle plugin install bundler-alias
                bundle config set aliases 'openvox:puppet'
          - name: Run tests
            run: bundle exec rake parallel_spec
